import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
  ]),
  {
    // components/ui/** is generated by `npx shadcn@latest add` and
    // regenerated verbatim from the upstream registry — it must never be
    // hand-edited to satisfy our stricter lint rules. embla-carousel's
    // generated carousel.tsx trips react-hooks/set-state-in-effect; relax
    // that rule for this CLI-owned directory only.
    files: ["components/ui/**"],
    rules: {
      "react-hooks/set-state-in-effect": "off",
    },
  },
]);

export default eslintConfig;
